window.JIFF_SCHEDULE_CONFIG = Object.freeze({
  sectionColors: {
    '코리안시네마': '#e07b39',
    '국제경쟁': '#4a9edd',
    '한국경쟁': '#e05c7a',
    '한국단편경쟁': '#d4886a',
    '월드시네마': '#5ab87a',
    '프론트라인': '#a06ecf',
    '시네마천국': '#4ac4c4',
    '시네필전주': '#7a9ab8',
    '마스터즈': '#d4a82a',
    '영화보다 낯선': '#b86aaa',
    '가능한 영화': '#7ab84a',
    '홍콩귀환': '#e07a55',
    '불면의 밤': '#5a5a9a',
    '개막작': '#d4a82a',
    '폐막작': '#d4a82a',
    '전주시네마프로젝트': '#3ab8b8',
    'J 스페셜': '#a8b84a',
    '특별상영': '#8a8a5a',
    '특별전: 조금 낯선 안성기를 만나다': '#7a9a7a',
    '특별전: 뉴욕 언더그라운드': '#9a7a6a',
    '특별전: 전주X마중': '#7a8a9a',
    '특별상영: 지역쇼케이스': '#6a8a6a',
    '특별상영: 가치봄': '#8aaa6a',
    '게스트 시네필': '#c48a3a',
    '세미나': '#5a5a5a',
  },
  venueGroups: [
    { id: 'cgv', label: 'CGV 전주고사', color: '#4a8ed4', match: venue => venue.startsWith('CGV') },
    { id: 'mega', label: '메가박스 전주객사', color: '#d4884a', match: venue => venue.startsWith('메가박스') },
    { id: 'other', label: '기타 상영관', color: '#7a9a7a', match: venue => !venue.startsWith('CGV') && !venue.startsWith('메가박스') },
  ],
  days: [
    { date: '2026-04-29', label: '4/29', sub: '수' },
    { date: '2026-04-30', label: '4/30', sub: '목' },
    { date: '2026-05-01', label: '5/1', sub: '금' },
    { date: '2026-05-02', label: '5/2', sub: '토' },
    { date: '2026-05-03', label: '5/3', sub: '일' },
    { date: '2026-05-04', label: '5/4', sub: '월' },
    { date: '2026-05-05', label: '5/5', sub: '화' },
    { date: '2026-05-06', label: '5/6', sub: '수' },
    { date: '2026-05-07', label: '5/7', sub: '목' },
    { date: '2026-05-08', label: '5/8', sub: '금' },
  ],
  legendSections: [
    '코리안시네마',
    '국제경쟁',
    '한국경쟁',
    '한국단편경쟁',
    '월드시네마',
    '마스터즈',
    '시네필전주',
    '시네마천국',
    '프론트라인',
    '영화보다 낯선',
    '가능한 영화',
    '홍콩귀환',
    '불면의 밤',
    'J 스페셜',
    '전주시네마프로젝트',
    '개막작',
  ],
  densityModes: [
    { id: 'auto', label: '자동' },
    { id: 'compact', label: '콤팩트' },
    { id: 'default', label: '기본' },
    { id: 'wide', label: '넓게' },
  ],
  densityProfiles: Object.freeze({
    compact: Object.freeze({
      bodyFont: 12,
      uiFont: 10,
      smallFont: 10,
      tinyFont: 9,
      tabFont: 11,
      logoFont: 17,
      logoSubFont: 11,
      tooltipTitleFont: 13,
      bookmarkTitleFont: 11,
      rowHeight: 38,
      labelWidth: 148,
      headerHeight: 52,
      scale: 1.34,
    }),
    default: Object.freeze({
      bodyFont: 13,
      uiFont: 11,
      smallFont: 11,
      tinyFont: 10,
      tabFont: 12,
      logoFont: 18,
      logoSubFont: 12,
      tooltipTitleFont: 14,
      bookmarkTitleFont: 12,
      rowHeight: 42,
      labelWidth: 160,
      headerHeight: 56,
      scale: 1.5,
    }),
    wide: Object.freeze({
      bodyFont: 14.5,
      uiFont: 12.5,
      smallFont: 12.5,
      tinyFont: 11,
      tabFont: 13,
      logoFont: 21,
      logoSubFont: 13,
      tooltipTitleFont: 16,
      bookmarkTitleFont: 13.5,
      rowHeight: 48,
      labelWidth: 184,
      headerHeight: 64,
      scale: 1.72,
    }),
  }),
  autoDensityRules: Object.freeze({
    wideMinWidth: 1680,
    wideMinHeight: 880,
    compactMaxWidth: 1280,
    compactMaxHeight: 760,
  }),
  timeRange: Object.freeze({
    start: 9 * 60 + 30,
    end: 24 * 60,
    initialScroll: 10 * 60,
  }),
  defaultState: Object.freeze({
    currentDay: '2026-04-29',
    activeGroups: ['cgv', 'mega', 'other'],
    densityMode: 'auto',
  }),
});
