const EVENT_PAGE_URLS = Object.freeze({
  masterclass: 'https://27kor.jeonjufest.kr/event/class_Master.asp',
  screeningsTalk: 'https://27kor.jeonjufest.kr/event/class_screenings.asp',
  smartTalk: 'https://27kor.jeonjufest.kr/event/smart_talk.asp',
  jSpecial: 'https://27kor.jeonjufest.kr/event/j_special.asp',
  xMajung: 'https://27kor.jeonjufest.kr/event/cine_tour_welcome.asp',
  jeonjuWide: 'https://27kor.jeonjufest.kr/event/jeonju_wide.asp',
});

const LINKED_PROGRAM_EVENTS_BY_CODE = Object.freeze({
  '130': Object.freeze({ label: '영특한 대화', durationMinutes: 60, url: EVENT_PAGE_URLS.smartTalk }),
  '133': Object.freeze({ label: '마중클래스', durationMinutes: 50, url: EVENT_PAGE_URLS.xMajung }),
  '146': Object.freeze({ label: '영화로의 여행', durationMinutes: 60, url: EVENT_PAGE_URLS.screeningsTalk }),
  '148': Object.freeze({ label: 'J 스페셜클래스', durationMinutes: 60, url: EVENT_PAGE_URLS.jSpecial }),
  '165': Object.freeze({ label: '마중클래스', durationMinutes: 50, url: EVENT_PAGE_URLS.xMajung }),
  '174': Object.freeze({ label: '마중클래스', durationMinutes: 50, url: EVENT_PAGE_URLS.xMajung }),
  '210': Object.freeze({ label: 'J 스페셜클래스', durationMinutes: 60, url: EVENT_PAGE_URLS.jSpecial }),
  '217': Object.freeze({ label: '라이브톤', durationMinutes: 60, url: EVENT_PAGE_URLS.smartTalk, searchText: '영특한 대화 라이브톤' }),
  '220': Object.freeze({ label: '영특한 대화', durationMinutes: 60, url: EVENT_PAGE_URLS.smartTalk }),
  '221': Object.freeze({ label: '영특한 대화', durationMinutes: 90, url: EVENT_PAGE_URLS.smartTalk }),
  '236': Object.freeze({ label: '마중클래스', durationMinutes: 50, url: EVENT_PAGE_URLS.xMajung }),
  '245': Object.freeze({ label: 'J 스페셜클래스', durationMinutes: 60, url: EVENT_PAGE_URLS.jSpecial }),
  '255': Object.freeze({ label: '마중클래스', durationMinutes: 50, url: EVENT_PAGE_URLS.xMajung }),
  '262': Object.freeze({ label: '마스터클래스', durationMinutes: 90, url: EVENT_PAGE_URLS.masterclass }),
  '280': Object.freeze({ label: '마중클래스', durationMinutes: 50, url: EVENT_PAGE_URLS.xMajung }),
  '301': Object.freeze({ label: 'J 스페셜클래스', durationMinutes: 60, url: EVENT_PAGE_URLS.jSpecial }),
  '315': Object.freeze({ label: '마중클래스', durationMinutes: 50, url: EVENT_PAGE_URLS.xMajung }),
  '326': Object.freeze({ label: '영특한 대화', durationMinutes: 60, url: EVENT_PAGE_URLS.smartTalk }),
  '327': Object.freeze({ label: '영특한 대화', durationMinutes: 90, url: EVENT_PAGE_URLS.smartTalk }),
  '328': Object.freeze({ label: '전주와이드토크', durationMinutes: 40, url: EVENT_PAGE_URLS.jeonjuWide, searchText: '전주 와이드 토크 Through the Lens 후지필름코리아' }),
  '334': Object.freeze({ label: '영화로의 여행', durationMinutes: 60, url: EVENT_PAGE_URLS.screeningsTalk }),
  '336': Object.freeze({ label: '마중클래스', durationMinutes: 50, url: EVENT_PAGE_URLS.xMajung }),
  '344': Object.freeze({ label: '마스터클래스', durationMinutes: 90, url: EVENT_PAGE_URLS.masterclass }),
  '346': Object.freeze({ label: 'J 스페셜클래스', durationMinutes: 60, url: EVENT_PAGE_URLS.jSpecial }),
  '347': Object.freeze({ label: '마중클래스', durationMinutes: 50, url: EVENT_PAGE_URLS.xMajung }),
  '348': Object.freeze({ label: '영화로의 여행', durationMinutes: 60, url: EVENT_PAGE_URLS.screeningsTalk }),
  '349': Object.freeze({ label: '영특한 대화', durationMinutes: 60, url: EVENT_PAGE_URLS.smartTalk }),
  '357': Object.freeze({ label: '영특한 대화', durationMinutes: 60, url: EVENT_PAGE_URLS.smartTalk }),
  '368': Object.freeze({ label: '영특한 대화', durationMinutes: 60, url: EVENT_PAGE_URLS.smartTalk }),
  '372': Object.freeze({ label: '전주와이드토크', durationMinutes: 40, url: EVENT_PAGE_URLS.jeonjuWide, searchText: '전주 와이드 토크 Behind the 辛 농심 신라면 GV' }),
  '420': Object.freeze({ label: '영특한 대화', durationMinutes: 90, url: EVENT_PAGE_URLS.smartTalk }),
  '423': Object.freeze({ label: '전주와이드토크', durationMinutes: 40, url: EVENT_PAGE_URLS.jeonjuWide, searchText: '전주 와이드 토크 Behind the 辛 농심 신라면 GV' }),
  '435': Object.freeze({ label: '영화로의 여행', durationMinutes: 60, url: EVENT_PAGE_URLS.screeningsTalk }),
  '454': Object.freeze({ label: '영화로의 여행', durationMinutes: 60, url: EVENT_PAGE_URLS.screeningsTalk }),
  '501': Object.freeze({ label: '전주와이드토크', durationMinutes: 40, url: EVENT_PAGE_URLS.jeonjuWide, searchText: '전주 와이드 토크 Through the Lens 후지필름코리아' }),
  '510': Object.freeze({
    label: '영화로의 여행',
    durationMinutes: 90,
    scheduleMode: 'separate',
    separateDate: '2026-05-05',
    separateStartTime: '11:00',
    separateVenue: '전주시네마타운 7관',
    url: EVENT_PAGE_URLS.screeningsTalk,
  }),
  '516': Object.freeze({ label: '영화로의 여행', durationMinutes: 60, url: EVENT_PAGE_URLS.screeningsTalk }),
  '525': Object.freeze({ label: '영특한 대화', durationMinutes: 60, url: EVENT_PAGE_URLS.smartTalk }),
  '614': Object.freeze({ label: '전주와이드토크', durationMinutes: 40, url: EVENT_PAGE_URLS.jeonjuWide, searchText: '전주 와이드 토크 Behind the 辛 농심 신라면 GV' }),
  '628': Object.freeze({ label: '영특한 대화', durationMinutes: 90, url: EVENT_PAGE_URLS.smartTalk }),
  '638': Object.freeze({ label: '영화로의 여행', durationMinutes: 60, url: EVENT_PAGE_URLS.screeningsTalk }),
  '643': Object.freeze({ label: '영특한 대화', durationMinutes: 60, url: EVENT_PAGE_URLS.smartTalk }),
  '674': Object.freeze({ label: '영특한 대화', durationMinutes: 60, url: EVENT_PAGE_URLS.smartTalk }),
  '729': Object.freeze({ label: '영특한 대화', durationMinutes: 60, url: EVENT_PAGE_URLS.smartTalk }),
});

window.JIFF_SCHEDULE_CONFIG = Object.freeze({
  sectionColors: {
    '코리안시네마': '#e07b39',
    '국제경쟁': '#4a9edd',
    '한국경쟁': '#e05c7a',
    '한국단편경쟁': '#d4886a',
    '월드시네마': '#5ab87a',
    '프론트라인': '#a06ecf',
    '시네마천국': '#4ac4c4',
    '시네필전주': '#7a9ab8',
    '마스터즈': '#d4a82a',
    '영화보다 낯선': '#b86aaa',
    '가능한 영화': '#7ab84a',
    '홍콩귀환': '#e07a55',
    '불면의 밤': '#5a5a9a',
    '개막작': '#d4a82a',
    '폐막작': '#d4a82a',
    '전주시네마프로젝트': '#3ab8b8',
    'J 스페셜': '#a8b84a',
    '특별상영': '#8a8a5a',
    '특별전: 조금 낯선 안성기를 만나다': '#7a9a7a',
    '특별전: 뉴욕 언더그라운드': '#9a7a6a',
    '특별전: 전주X마중': '#7a8a9a',
    '특별상영: 지역쇼케이스': '#6a8a6a',
    '특별상영: 가치봄': '#8aaa6a',
    '게스트 시네필': '#c48a3a',
    '세미나': '#5a5a5a',
  },
  venueGroups: [
    { id: 'cgv', label: 'CGV 전주고사', color: '#4a8ed4', match: venue => venue.startsWith('CGV') },
    { id: 'mega', label: '메가박스 전주객사', color: '#d4884a', match: venue => venue.startsWith('메가박스') },
    { id: 'other', label: '기타 상영관', color: '#7a9a7a', match: venue => !venue.startsWith('CGV') && !venue.startsWith('메가박스') },
  ],
  days: [
    { date: '2026-04-29', label: '4/29', sub: '수' },
    { date: '2026-04-30', label: '4/30', sub: '목' },
    { date: '2026-05-01', label: '5/1', sub: '금' },
    { date: '2026-05-02', label: '5/2', sub: '토' },
    { date: '2026-05-03', label: '5/3', sub: '일' },
    { date: '2026-05-04', label: '5/4', sub: '월' },
    { date: '2026-05-05', label: '5/5', sub: '화' },
    { date: '2026-05-06', label: '5/6', sub: '수' },
    { date: '2026-05-07', label: '5/7', sub: '목' },
    { date: '2026-05-08', label: '5/8', sub: '금' },
  ],
  legendSections: [
    '코리안시네마',
    '국제경쟁',
    '한국경쟁',
    '한국단편경쟁',
    '월드시네마',
    '마스터즈',
    '시네필전주',
    '시네마천국',
    '프론트라인',
    '영화보다 낯선',
    '가능한 영화',
    '홍콩귀환',
    '불면의 밤',
    'J 스페셜',
    '전주시네마프로젝트',
    '개막작',
  ],
  densityModes: [
    { id: 'auto', label: '자동' },
    { id: 'compact', label: '좁게' },
    { id: 'default', label: '기본' },
    { id: 'wide', label: '넓게' },
  ],
  densityProfiles: Object.freeze({
    compact: Object.freeze({
      bodyFont: 12,
      uiFont: 10,
      smallFont: 10,
      tinyFont: 9,
      tabFont: 11,
      logoFont: 17,
      logoSubFont: 11,
      tooltipTitleFont: 13,
      bookmarkTitleFont: 11,
      rowHeight: 38,
      labelWidth: 148,
      headerHeight: 52,
      scale: 1.34,
    }),
    default: Object.freeze({
      bodyFont: 13,
      uiFont: 11,
      smallFont: 11,
      tinyFont: 10,
      tabFont: 12,
      logoFont: 18,
      logoSubFont: 12,
      tooltipTitleFont: 14,
      bookmarkTitleFont: 12,
      rowHeight: 42,
      labelWidth: 160,
      headerHeight: 56,
      scale: 1.5,
    }),
    wide: Object.freeze({
      bodyFont: 14.5,
      uiFont: 12.5,
      smallFont: 12.5,
      tinyFont: 11,
      tabFont: 13,
      logoFont: 21,
      logoSubFont: 13,
      tooltipTitleFont: 16,
      bookmarkTitleFont: 13.5,
      rowHeight: 48,
      labelWidth: 184,
      headerHeight: 64,
      scale: 1.72,
    }),
  }),
  autoDensityRules: Object.freeze({
    wideMinWidth: 1680,
    wideMinHeight: 880,
    compactMaxWidth: 1280,
    compactMaxHeight: 760,
  }),
  timeRange: Object.freeze({
    start: 9 * 60 + 30,
    end: 24 * 60,
    initialScroll: 10 * 60,
  }),
  defaultState: Object.freeze({
    currentDay: '2026-04-29',
    activeGroups: ['cgv', 'mega', 'other'],
    densityMode: 'auto',
  }),
  linkedProgramEventsByCode: LINKED_PROGRAM_EVENTS_BY_CODE,
});
