window.JIFF_TALKTALK_DATA = Object.freeze({
  overview: Object.freeze({
    venue: '전주시네마타운 7관',
    durationMinutes: 40,
    feeLabel: '12,000원(영화 미포함)',
    note: '별도 영어 통역은 제공되지 않습니다.',
    pageUrl: 'https://jeonjufest.kr/event/jeonju_talktalk.asp',
    description: '영화와 영화의 경계를 넘어선 다양한 콘텐츠의 흥미로운 막후 이야기를 하는 가벼운 영화 수다로, 전주시네마타운 7관에서 관객과 지역 주민이 함께 만나는 토크 프로그램입니다.',
  }),
  items: Object.freeze([
    Object.freeze({
      code: '1001',
      date: '2026-05-01',
      startTime: '11:00',
      seriesLabel: '전주톡톡 1',
      title: '박세영과 정회린',
      summary: '두 사람의 예술적 파트너십을 심도 있게 파헤치며, 작품들을 통해 보여준 미학적 동행에 대한 진솔한 이야기를 나눈다.',
      guestLabel: '박세영(감독), 정회린(배우)',
      moderator: '차한비(영화웹진 『리버스』 기자)',
    }),
    Object.freeze({
      code: '1002',
      date: '2026-05-01',
      startTime: '14:00',
      seriesLabel: '전주톡톡 2',
      title: '프로의 기술, 초심의 마음',
      summary: '베테랑 배우도 카메라 앞에선 늘 처음과 같은 마음으로. 탄탄한 연기 내공 속에서도 초심을 잃지 않고 연기하는 배우들의 원동력에 대해 진솔한 이야기를 나눈다.',
      guestLabel: '이영진(배우)',
      moderator: '오지은(뮤지션, 작가)',
    }),
    Object.freeze({
      code: '1003',
      date: '2026-05-01',
      startTime: '17:00',
      seriesLabel: '전주톡톡 3',
      title: '김종관이 사랑한 피사체',
      summary: '김종관 감독에 빠질 수밖에 없는, 연우진 배우를 담을 수밖에 없는, 서로에게 필수 불가결한 존재인 감독과 배우의 케미를 탐구하는 시간을 갖는다.',
      guestLabel: '김종관(감독), 연우진(배우)',
      moderator: '진명현(무브먼트 대표)',
    }),
    Object.freeze({
      code: '1004',
      date: '2026-05-01',
      startTime: '19:00',
      seriesLabel: '전주톡톡 4',
      title: '전주메이커스: 모더레이터란 말이죠',
      summary: 'GV에 빠져들게 하는 진행 노하우와 봄날의 전주에서 겪었던 잊지 못할 순간들을 이야기하는 영화인 직업 탐구생활 모더레이터 편이다.',
      guestLabel: '이다혜(『씨네21』 기자), 진명현(무브먼트 대표), 차한비(영화웹진 『리버스』 기자)',
      moderator: '박준호(감독)',
    }),
    Object.freeze({
      code: '1005',
      date: '2026-05-02',
      startTime: '11:00',
      seriesLabel: '전주톡톡 5',
      title: '앞으로 나아가야 할 방향: 지속 가능한 광장',
      summary: '아고라에서 광장으로, 연대의 공간을 넘어 상징이 된 광장의 입체적인 가치와 지금 우리에게 남긴 오늘날 민주주의에 대해 함께 이야기한다.',
      guestLabel: '문정현(감독), 김종관(감독), 김종우, 김신완(감독)',
      moderator: '차한비(영화웹진 『리버스』 기자)',
    }),
    Object.freeze({
      code: '1006',
      date: '2026-05-02',
      startTime: '14:00',
      seriesLabel: '전주톡톡 6',
      title: '나 혼자 한다, 제작부터 배급까지',
      summary: '<고백하지마> 류현경 감독과 <잔챙이> 김호원 배우가 제작부터 배급까지 독자적으로 진행한 이야기를 들려주며, 레이스 중 마주한 어려움과 기쁨을 함께 공유한다.',
      guestLabel: '류현경(류네 대표), 김호원(배우)',
      moderator: '이태동(감독)',
    }),
    Object.freeze({
      code: '1007',
      date: '2026-05-02',
      startTime: '17:00',
      seriesLabel: '전주톡톡 7',
      title: '전주메이커스: 배우란 말이죠',
      summary: '캐릭터를 구축하고 감정을 설계해 나가는 과정부터 현장과 카메라 앞에서의 실제 경험까지, 배우의 삶을 함께 이야기한다.',
      guestLabel: '김현목(배우), 이명하(배우)',
      moderator: '차한비(영화웹진 『리버스』 기자)',
    }),
    Object.freeze({
      code: '1008',
      date: '2026-05-02',
      startTime: '19:00',
      seriesLabel: '전주톡톡 8',
      title: '전주톡톡X필르머: 배우의 은밀한 제작생활',
      summary: '영화 제작사 필르머(FILMER)의 고경표, 강태우 배우가 제작 도전기와 차기 행보에 대한 이야기를 나누는 시간이다.',
      guestLabel: '고경표(배우), 강태우(배우)',
      moderator: '이태동(감독)',
    }),
    Object.freeze({
      code: '1009',
      date: '2026-05-03',
      startTime: '11:00',
      seriesLabel: '전주톡톡 9',
      title: '전주메이커스: 빛나는 포스터란 말이죠',
      summary: '처음 만나는 영화의 얼굴인 포스터의 제작기를 20주년을 맞이한 빛나는의 박시영 대표와 함께 이야기한다.',
      guestLabel: '박시영(빛나는 대표)',
      moderator: '차한비(영화웹진 『리버스』 기자)',
    }),
    Object.freeze({
      code: '1010',
      date: '2026-05-03',
      startTime: '14:00',
      seriesLabel: '전주톡톡 10',
      title: '다정한 시네필 토크: 시네필을 찾아서',
      summary: '다양한 의미의 시네필을 유쾌하게 논의하며, 그들이 찾는 영화제와 독립영화를 함께 이야기하는 시간을 가진다.',
      guestLabel: '원소윤(작가, 스탠드업 코미디언), 박준호(감독)',
      moderator: '차한비(영화웹진 『리버스』 기자)',
    }),
    Object.freeze({
      code: '1011',
      date: '2026-05-03',
      startTime: '17:00',
      seriesLabel: '전주톡톡 11',
      title: '비하인디렉터스: 감독들은 뭐 하고 놀까?',
      summary: '변영주, 이원석, 이해영 감독의 틈 시간을 본격적으로 파고들며, 쉬는 시간의 취향과 리듬을 가볍고 솔직하게 묻는다.',
      guestLabel: '변영주(감독), 이원석(감독), 이해영(감독)',
      moderator: '차한비(영화웹진 『리버스』 기자)',
    }),
  ]),
});
